services:
  db:
    image: mariadb:latest
    container_name: klodworld-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: klodonline
      MYSQL_USER: klodadmin
      MYSQL_PASSWORD: Pw3Lqb6fuLspT7IrYp
    volumes:
      - db_data:/var/lib/mysql
      - ./setup/worldserver.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - klodworld-net

  php:
    image: bitnami/php-fpm:latest
    container_name: klodworld-php
    volumes: 
    - .:/app 
    depends_on:
      - db
    networks:
      - klodworld-net

  apache:
    image: bitnami/apache:latest
    container_name: klodworld-apache
    ports:
      - "2443:8443"
    depends_on:
      - php
    networks:
      - klodworld-net
    volumes:
      - ./www:/app 
      - ./common:/common
      - ./setup/apache.conf:/vhosts/klodworld.conf:ro

  node:
    build:
      context: .
      dockerfile: chat/Dockerfile
    container_name: klodworld-node
    ports:
      - "2080:8080"
    volumes: 
      - ./chat:/app 
      - ./common:/common
    depends_on:
      - apache
    networks:
      - klodworld-net
    command: "npm start"

  game:
    build:
      context: .
      dockerfile: game/Dockerfile
    container_name: klodworld-game
    volumes:
      - ./game:/var/klodworld/game
      - ./common:/var/klodworld/common
    depends_on:
      - db
    networks:
      - klodworld-net
    restart: always

volumes:
  db_data:

networks:
  klodworld-net:
